# The host to listen on.
host: 0.0.0.0
# The port to listen on.
port: 3000
# The directory in which to store the LevelDB database.
databasePlugin: LevelDB
databaseConfig:
  databaseDataDirectory: db
fileStoragePlugin: LocalFiles
fileStorageConfig:
  # The directory in which to store uploaded file assets.
  fileDataDirectory: files
# Determines the cipher used to encrypt the assets.
# See https://www.openssl.org/docs/manmaster/apps/ciphers.html for options.
encryptionCipher: 'aes-256-cbc'
encryptionPassword: SECRET

recipheredOutputDir: null

# API tokens for creating all routes except asset upload (disabled by default)
tokens: null

uploadsPaused: false

## If using S3 use this template for config settings.
#
# fileStoragePlugin: AwsS3Storage
# fileStorageConfig:
#   awsAccessKeyId: [KEY ID FOR BUCKET]
#   awsSecretAccessKey: [BUCKET SECRET KEY]
#   awsBucket: [BUCKET NAME]

