#! /usr/bin/env node
'use strict';

var Loader = require('yaml-config-loader');
var yargs = require('yargs');
var path = require('path');
var bunyan = require('bunyan');
var through2 = require('through2');

var plugins = require('../lib/plugins');

var loader = new Loader({stopOnError: false});
var logger = bunyan.createLogger({name: 'probo-asset-fixer'});

var cliargs = yargs
  .describe('config', 'A path to a one or more configuration files or directories.')
  .alias('config', 'c');

var argv = cliargs.argv;

if (argv.help) {
  cliargs.showHelp();
  throw new Error();
}

loader.on('error', function(error) {
  // Ignore errors due to missing files.
});

loader.add(path.join(__dirname, '..', 'defaults.config.yaml'), {filterKeys: true});
loader.addAndNormalizeObject(process.env);

if (argv.config) {
  if (typeof argv.config === 'string') {
    argv.config = [argv.config];
  }
  argv.config.forEach(function(arg) {
    loader.add(path.resolve(arg));
  });
}

loader.addAndNormalizeObject(argv);

loader.load(function(error, config) {
  config = config || {};
  config.databasePlugin = 'LevelDB';
  config.database = new plugins.database[config.databasePlugin](config.databaseConfig, logger);

  // Used to generate IDs for asset uploads.
  var assetIds = [];
  var dbStream = config.database.listAssets();

  dbStream.on('data', function(data) {
    var assetData = {
      assetId: data.assetId,
      token: data.metadata.token,
    };

    assetIds.push(assetData);
  })
  .on('error', function(err) {
    console.error(err);
    return;
  })
  .on('end', function() {
    assetIds.forEach(function(asset) {
      console.log(`Fixing asset: ${asset.assetId}`);
      config.database.getBucketFromToken(asset.token, function(err, bucketId) {
        findAndRepairBucketAsset(bucketId, asset.assetId, config);
      });
    });
  });

});


function findAndRepairBucketAsset(bucketId, assetId, config) {
  config.database.listOldBucketsAssets(bucketId)
    .pipe(through2.obj(function(data, enc, cb) {
      var parts = data.key.split('!!');
      if (parts.length === 4) {
        if (parts[1] === bucketId && parts[3] === assetId) {
          repairBucketAsset(bucketId, assetId, parts[2], data.value, config);
        }
      }
      else if (parts.length > 4) {
        console.warn('Possible error at: ', data.key);
      }
      cb();
    }));
}

function repairBucketAsset(bucketId, assetId, assetName, value, config) {
  config.database.addAssetNameToAssetMetadata(assetId, assetName, function(err) {
    if (err) {
      console.error('Could not update asset metadata for asset: ' + assetId);
      return;
    }
    console.log(`Updated metadata: "asset!!${assetId}"`);
  });

  config.database.createBucketAssetVersion(bucketId, assetId, assetName, value, function(err) {
    if (err) {
      console.error('Failed to repair bucket asset:');
      console.error(`bucket!!${bucketId}!!${assetName}!!${assetId}`);
      return;
    }
    console.log(`Created: "bucket-asset-version!!${bucketId}!!${assetName}!!${assetId}"`);
    config.database.deleteOldBucketVersion(bucketId, assetId, assetName, function(err) {
      if (err) {
        console.error('Failed to delete old bucket version:');
        console.error(`bucket!!${bucketId}!!${assetName}!!${assetId}`);
        return;
      }
      console.log(`Removed: "bucket!!${bucketId}!!${assetName}!!${assetId}"`);
      createBucketAsset(bucketId, assetName, config);
    });
  });
}

function createBucketAsset(bucketId, assetName, config) {
  config.database.getOldAssetId(bucketId, assetName, function(err, assetId) {
    if (err) {
      console.error('Failed to retreive bucket asset:');
      console.error(`bucket!!${bucketId}!!asset!!${assetName}`);
      return;
    }

    config.database.createBucketAsset(bucketId, assetName, assetId, function(err) {
      if (err) {
        console.error('Failed to create bucket asset:');
        console.error(`bucket-asset!!${bucketId}!!${assetName}`);
        return;
      }
      console.log(`Created: "bucket-asset!!${bucketId}!!${assetName}"`);
      config.database.deleteOldBucketAsset(bucketId, assetName, function(err) {
        if (err) {
          console.error('Failed to remove bucket asset:');
          console.error(`bucket!!${bucketId}!!asset!!${assetName}`);
          return;
        }
        console.log(`Removed: "bucket!!${bucketId}!!asset!!${assetName}"`);
      });
    });
  });
}
